basePath: /
definitions:
  game.PlayerState:
    properties:
      cardCount:
        type: integer
      cards:
        items:
          type: string
        type: array
      id:
        type: string
      name:
        type: string
    type: object
  game.StateResponse:
    properties:
      gameId:
        type: string
      hasStarted:
        type: boolean
      players:
        items:
          $ref: '#/definitions/game.PlayerState'
        type: array
      requesterId:
        type: string
    type: object
  model.GameSessionLog:
    properties:
      createdAt:
        type: string
      gameId:
        type: string
      id:
        type: string
      message:
        type: string
      type:
        type: string
      userId:
        type: string
    type: object
info:
  contact: {}
  description: API for the Donkey card game
  title: Donkey API
  version: "1.0"
paths:
  /api/game/logs:
    get:
      description: Retrieves chat and status logs for a game in reverse chronological
        order
      parameters:
      - description: Game ID
        in: query
        name: gameId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.GameSessionLog'
            type: array
      summary: List session logs
      tags:
      - events
  /api/game/state:
    get:
      description: Returns current game state tailored for the requesting user
      parameters:
      - description: Game ID
        in: query
        name: gameId
        required: true
        type: string
      - description: User ID
        in: query
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/game.StateResponse'
      summary: Get game state
      tags:
      - game
  /api/game/stream:
    get:
      description: Streams session and state change events for a game
      parameters:
      - description: Game ID
        in: query
        name: gameId
        required: true
        type: string
      - description: User ID
        in: query
        name: userId
        required: true
        type: string
      produces:
      - text/event-stream
      responses:
        "200":
          description: event stream
          schema:
            type: string
      summary: Stream game updates
      tags:
      - events
  /api/hello:
    get:
      description: Simple hello world endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Returns a greeting
      tags:
      - example
  /api/version:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get server version
      tags:
      - meta
swagger: "2.0"
